### ISSUE TITLE
LiveStream data.type sometimes == 'remove' with data.value == undefined when used with crdt

### ISSUE THREAD

**Issue by nrw** [dominictarr/level-scuttlebutt#11]
Referring to this line:

https://github.com/dominictarr/level-scuttlebutt/blob/master/index.js#L151

I just want to document that this behavior exists as it seems to be a problem. When used to persist a `crdt`, sometimes a data with type `remove` is emitted. `undefined` is passed to `JSON.parse`, which throws. Adding `if(data.type == 'remove') return` right below that line removes this issue. However, I don't know if this is a problem with this module or with `crdt` (or something else).

**Comment by dominictarr** [comment]
hmm, it emits `data.type = 'remove'` I think that should be `'del'`.
Can you show be the stack trace?

Are the tests passing for you?

**Comment by nrw** [comment]
After some `npm install`s: yes, tests are passing. It appears that the batch operation of `level-js` converts `del` to `remove`.

https://github.com/maxogden/level.js/blob/master/index.js#L66-L72

I'll take this up there. Sorry to spam your issues!
