### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by juliangruber** [dominictarr/level-scuttlebutt#9]
I've been testing scuttlebutt replication for a bit and it seems to work very well, but I'm not sure if I'm using it correctly.

https://github.com/juliangruber/level-scuttlebutt-test/blob/master/index.js

I've seen `db.scuttlebutt.createReplicateStream` and `db.createStream` and other things in your code, so I'm not sure what to use.

**Comment by dominictarr** [comment]
`createReplicateStream` is for replicating the entire scuttlebutt db,
and `createStream` is for creating a stream to `level-scuttlebutt/client`

hmm, this stuff needs to be documented...

**Comment by juliangruber** [comment]
ok, I tested that here: https://github.com/juliangruber/level-scuttlebutt-test/compare/create-replicate-stream

and see no replication happening

**Comment by dominictarr** [comment]
you are attempting to replicate between 1 level-scuttlebutt instance and itself.
also, I think you need to wait for the server to bind before you create a connection to it (when working within one process)

``` js
net.createServer(function (stream) {
  //connected
}).listen(PORT, function () {
  var stream = net.connect(PORT)
  //connected
})
```

**Comment by juliangruber** [comment]
there's a timeout of 1s between processes start, so the prior server should already be up.
and with `node test.js 2` it starts two processes and makes them connect to each other.

**Comment by dominictarr** [comment]
Aha, I see what the error is!
the mistake is that level replicate only swaps the scuttlebutts for the nodes that are currently in the database,
so when you add another scuttlebutt after you have started replicating, it fails.

I have one test for `createReplicateStream`, https://github.com/dominictarr/level-scuttlebutt/blob/master/test/script.js
but it doesn't cover this case.

Can you make a pull request that adds a failing test case to level-scuttlebutt?
you could adapt https://github.com/dominictarr/level-scuttlebutt/blob/master/test/script.js but just make sure that the nodes are connected before you start adding data to them.
